services:
  app:
    image: etl
    volumes:
      - ./output:/app/output
    depends_on:
      - postgres
    networks:
      - my-network
    command: ["process_data.py","batch1.csv"]
  app2:
    image: etl
    volumes:
      - ./output:/app/output
    depends_on:
      - postgres
    networks:
      - my-network
    command: ["process_data.py","batch2.csv"]
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydata
      POSTGRES_USER: balu
      POSTGRES_PASSWORD: bn
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
  dashboard:
    image: etl
    ports: 
      - 8501:8501
    depends_on:
      - postgres
    networks:
      - my-network
    command: ["-m", "streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  pgdata:
networks:
  my-network:
    driver: bridge
